### PR TITLE
resolve deprecated selector

### LINKED ISSUE #5: Deprecated selector in `Chromodynamics/index.less`
In `Chromodynamics/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor.is-focused .cursor,
:host(.is-focused) .cursor` => `atom-text-editor.is-focused .cursor,atom-text-editor .cursor`

* `atom-text-editor.is-focused .selection .region,
:host(.is-focused) .selection .region` => `atom-text-editor.is-focused .selection .region,atom-text-editor .selection .region`

* `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,
:host(.is-focused) .line-number.cursor-line-no-selection,
:host(.is-focused) .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line`

* `.text,
.source` => `.syntax--text,
.syntax--source`

* `.comment` => `.syntax--comment`

* `.string` => `.syntax--string`

* `.string.quoted.docstring` => `.syntax--string.syntax--quoted.syntax--docstring`

* `.string.quoted.docstring .string` => `.syntax--string.syntax--quoted.syntax--docstring .syntax--string`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.constant.character,
.constant.other` => `.syntax--constant.syntax--character,
.syntax--constant.syntax--other`

* `.keyword` => `.syntax--keyword`

* `.comment.line.note,
.string.quoted.docstring.note` => `.syntax--comment.line.syntax--note,
.syntax--string.syntax--quoted.syntax--docstring.syntax--note`

* `.storage` => `.syntax--storage`

* `.storage.type` => `.syntax--storage.syntax--type`

* `.entity.name.class` => `.syntax--entity.syntax--name.syntax--class`

* `.entity.other.inherited-class` => `.syntax--entity.syntax--other.syntax--inherited-class`

* `.entity.name.function` => `.syntax--entity.syntax--name.syntax--function`

* `.variable.parameter` => `.syntax--variable.syntax--parameter`

* `.entity.name.tag.namespace` => `.syntax--entity.syntax--name.syntax--tag.syntax--namespace`

* `.entity.name.tag,
.keyword.doctype.xml` => `.syntax--entity.syntax--name.syntax--tag,
.syntax--keyword.syntax--doctype.syntax--xml`

* `.entity.other.attribute-name` => `.syntax--entity.syntax--other.syntax--attribute-name`

* `.support.function` => `.syntax--support.syntax--function`

* `.support.constant` => `.syntax--support.syntax--constant`

* `.support.type` => `.syntax--support.syntax--type`

* `.support.class,
.support.other,
.support.variable` => `.syntax--support.syntax--class,
.syntax--support.syntax--other,
.syntax--support.syntax--variable`

* `.invalid` => `.syntax--invalid`

* `.invalid.deprecated` => `.syntax--invalid.syntax--deprecated`

* `.meta.structure.dictionary.json .string.quoted.double.json` => `.syntax--meta.syntax--structure.syntax--dictionary.syntax--json .syntax--string.syntax--quoted.syntax--double.syntax--json`

* `.meta.diff,
.meta.diff.header` => `.syntax--meta.syntax--diff,
.syntax--meta.syntax--diff.syntax--header`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.variable.language.special,
.variable.parameter.function.language.special` => `.syntax--variable.syntax--language.syntax--special,
.syntax--variable.syntax--parameter.syntax--function.syntax--language.syntax--special`

* `.comment.typehint` => `.syntax--comment.syntax--typehint`

* `.comment.typehint.ignore` => `.syntax--comment.syntax--typehint.syntax--ignore`

* `.comment.typehint.type` => `.syntax--comment.syntax--typehint.syntax--type`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

### PR DESCRIPTION
**Pull request by reverbc**
Fix #5

### CODE REVIEW

**Comment by 1st1** [comment]
Thanks! Did you just regenerate atom schema using `make`?

**Comment by reverbc** [comment]
Uh no. I'm not that familiar with atom theme development (just started few minutes ago) so I manually merge the changes.

**Comment by 1st1** [comment]
Since atom scheme is autogenerated from the `tmTheme` file, we need to figure out how to update the `Makefile`. Otherwise, these changes will be lost next time we update the scheme.

**Comment by reverbc** [comment]
The regenerated less file has few differences with my hand-crafted one. I'll update that with this PR. Please hold.

**Comment by reverbc** [comment]
Hi @1st1 I've updated the theme and verified in my Atom. Could you help to check if it works on your environment too? Thanks.

**Comment by 1st1** [comment]
Is this a backwards compatible change btw? Will it work with Atom versions prior to v1.13.0?

**Comment by elprans** [comment]
It will not.  package.json engines.atom will have to be updated (>=1.13.0)

**Comment by reverbc** [comment]
No it's not. Just downloaded 1.12.7 and it doesn't work. I've included that change as well.

**Comment by 1st1** [comment]
Thanks @reverbc!

**Pull request merged**
